project: 'vae-test'

dataset:
    class_path: myvae.train.dataset.ImageDataset
    init_args:
        data_dir: 訓練用データセットへのパス（ここで指定したディレクトリの直下に画像を置く）

val_dataset:
    class_path: myvae.train.dataset.ImageDataset
    init_args:
        data_dir: 検証用データセットへのパス（ここで指定したディレクトリの直下に画像を置く）

dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        shuffle: true
        drop_last: true

val_dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        shuffle: false
        drop_last: true

model:
    config:
        encoder: {}
        decoder: {}

train:
    n_epochs: 50
    batch_size: 4
    grad_acc_steps: 8
    use_gradient_checkpointing: false
    log_freq: 32
    save_every_n_epochs: 5
    save_every_n_steps: 0
    validate_every_n_epochs: 1
    validate_every_n_steps: 0
    loss:
        - type: mse
          weight: 1.0
        - type: kld
          weight: 1e-6
    val_loss:
        - l1
        - mse
        - kld
        - gm
    #hf_repo_id: 'ここにHFの repo id を入れるとモデルファイルを自動でアップロードする'
    model_save_async: false
    optimizer:
        class_path: torch.optim.AdamW
        init_args:
            lr: 1e-5
    scheduler:
        class_path: torch.optim.lr_scheduler.ConstantLR
        init_args:
            factor: 1.0
            total_iters: 0
