project: 'vae-test'

dataset:
    class_path: myvae.train.dataset.ImageDataset
    init_args:
        data_dir: 'data/256x256/train'

val_dataset:
    class_path: myvae.train.dataset.ImageDataset
    init_args:
        data_dir: 'data/256x256/val'

dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        shuffle: true
        drop_last: true

model:
    config:
        encoder: {}
        decoder: {}

train:
    n_epochs: 50
    batch_size: 4
    grad_acc_steps: 8
    use_gradient_checkpointing: false
    log_freq: 32
    save_every_n_epochs: 0
    save_every_n_steps: 1000
    validate_every_n_epochs: 0
    validate_every_n_steps: 1000
    loss:
        - type: mse
          weight: 1.0
        - type: kld
          weight: 1e-6
    #hf_repo_id: 'ここにHFの repo id を入れるとモデルファイルを自動でアップロードする'
    optimizer:
        class_path: torch.optim.AdamW
        init_args:
            lr: 1e-5
    scheduler:
        class_path: torch.optim.lr_scheduler.ConstantLR
        init_args:
            factor: 1.0
            total_iters: 0
